In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="ticks", color_codes=True)

# Data load

In [2]:
train_activity = pd.read_csv('C:/Bigcontest/train_activity.csv')
test_activity = pd.read_csv('C:/Bigcontest/test_activity.csv')
train_label = pd.read_csv('C:/Bigcontest/train_label.csv')

# groupby.mean

In [3]:
train_activity_mean = train_activity.groupby(['acc_id'], as_index=False).mean()
test_activity_mean  = test_activity.groupby(['acc_id'], as_index=False).mean()

# Add 'label' 

In [4]:
train_activity_label = pd.merge(train_activity_mean, train_label, how='outer', on='acc_id')

## Divide into train set and test set. (Stratified)

In [5]:
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.3, random_state=42)
for train_index, test_index in split.split(train_activity_label, train_activity_label['label']):
    strat_train_set = train_activity_label.loc[train_index]
    strat_test_set = train_activity_label.loc[test_index]

In [6]:
strat_train_set.head()

acc_id   wk    cnt_dt  \
9787   18af352a486615c71e794eabd7de7dcbcfaaa8025d8c72...  5.0  4.833333   
54039  89f84ffac2303e3ce14df60c77c834d04de191ab467738...  8.0  3.000000   
62298  9f47d2a51bc7558b9a413b91c31fc88745278f199173a5...  8.0  6.000000   
59818  98cf8ba124fd558aa93872b166090d85d6546425985ea8...  4.5  6.750000   
15127  2659b4179d6c19405562c617d86510a14882196d816524...  6.0  6.200000   

       play_time   npc_exp  npc_hongmun  quest_exp  quest_hongmun  \
9787   -0.528608 -0.157050    -0.286200  -0.027648      -0.153857   
54039  -0.659798 -0.231874    -0.290803  -0.250423      -0.487666   
62298   2.075927  1.362542     0.417022   1.968807       1.861860   
59818  -0.264199 -0.231874    -0.157795  -0.250423      -0.418289   
15127   2.113040  2.264012     0.259738   1.954970       1.509933   

       item_hongmun  game_combat_time    ...     normal_chat  whisper_chat  \
9787      -0.302199         -0.476031    ...       -0.032859     -0.161998   
54039     -0.306354         -0.569842    ...       -0.034038     -0.231827   
62298     -0.136000          2.890492    ...        0.082671     -0.231827   
59818     -0.256754         -0.096771    ...       -0.034038     -0.150189   
15127     -0.041682          2.412227    ...        0.048012      0.024486   

       district_chat  party_chat  guild_chat  faction_chat  cnt_use_buffitem  \
9787       -0.016574   -0.268693   -0.343293     -0.024028         -0.389936   
54039      -0.016574   -0.275174   -0.343293     -0.024028         -0.503692   
62298      -0.016574   -0.275174   -0.343293     -0.024028          2.632727   
59818      -0.016574   -0.275174   -0.343293     -0.024028         -0.029708   
15127      -0.016574   -0.129137   -0.343293     -0.024028          1.627340   

       gathering_cnt  making_cnt     label  
9787       -0.027758   -0.365536     month  
54039      -0.027758   -0.365536     month  
62298      -0.027758    2.174423      week  
59818      -0.027758   -0.365536     month  
15127      -0.027758   -0.365536  retained  

[5 rows x 39 columns]

In [7]:
strat_train_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 70000 entries, 9787 to 77718
Data columns (total 39 columns):
acc_id                      70000 non-null object
wk                          70000 non-null float64
cnt_dt                      70000 non-null float64
play_time                   70000 non-null float64
npc_exp                     70000 non-null float64
npc_hongmun                 70000 non-null float64
quest_exp                   70000 non-null float64
quest_hongmun               70000 non-null float64
item_hongmun                70000 non-null float64
game_combat_time            70000 non-null float64
get_money                   70000 non-null float64
duel_cnt                    70000 non-null float64
duel_win                    70000 non-null float64
partybattle_cnt             70000 non-null float64
partybattle_win             70000 non-null float64
cnt_enter_inzone_solo       70000 non-null float64
cnt_enter_inzone_light      70000 non-null float64
cnt_enter_inzone_skill

In [8]:
strat_test_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30000 entries, 33550 to 18978
Data columns (total 39 columns):
acc_id                      30000 non-null object
wk                          30000 non-null float64
cnt_dt                      30000 non-null float64
play_time                   30000 non-null float64
npc_exp                     30000 non-null float64
npc_hongmun                 30000 non-null float64
quest_exp                   30000 non-null float64
quest_hongmun               30000 non-null float64
item_hongmun                30000 non-null float64
game_combat_time            30000 non-null float64
get_money                   30000 non-null float64
duel_cnt                    30000 non-null float64
duel_win                    30000 non-null float64
partybattle_cnt             30000 non-null float64
partybattle_win             30000 non-null float64
cnt_enter_inzone_solo       30000 non-null float64
cnt_enter_inzone_light      30000 non-null float64
cnt_enter_inzone_skil

In [9]:
strat_train_set['label'].value_counts()

month       17500
2month      17500
retained    17500
week        17500
Name: label, dtype: int64

In [10]:
strat_test_set['label'].value_counts()

week        7500
month       7500
2month      7500
retained    7500
Name: label, dtype: int64

# Attributes Drop(not yet)

In [11]:
strat_train_set_drop = strat_train_set
strat_test_set_drop = strat_test_set

In [12]:
strat_train_set_drop.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 70000 entries, 9787 to 77718
Data columns (total 39 columns):
acc_id                      70000 non-null object
wk                          70000 non-null float64
cnt_dt                      70000 non-null float64
play_time                   70000 non-null float64
npc_exp                     70000 non-null float64
npc_hongmun                 70000 non-null float64
quest_exp                   70000 non-null float64
quest_hongmun               70000 non-null float64
item_hongmun                70000 non-null float64
game_combat_time            70000 non-null float64
get_money                   70000 non-null float64
duel_cnt                    70000 non-null float64
duel_win                    70000 non-null float64
partybattle_cnt             70000 non-null float64
partybattle_win             70000 non-null float64
cnt_enter_inzone_solo       70000 non-null float64
cnt_enter_inzone_light      70000 non-null float64
cnt_enter_inzone_skill

# First Model

In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold

In [14]:
train_X_id = strat_train_set_drop['acc_id']
test_X_id = strat_test_set_drop['acc_id']

train_X = strat_train_set_drop.drop(['acc_id','label'],axis=1)
train_y = strat_train_set_drop['label']
test_X = strat_test_set_drop.drop(['acc_id','label'],axis=1)
test_y = strat_test_set_drop['label']
real_test = test_activity_mean.drop(['acc_id'], axis=1)
real_test_id= test_activity_mean['acc_id']

In [15]:
rand_fr_1 = RandomForestClassifier(random_state=42)

In [16]:
scores = cross_val_score(rand_fr_1, train_X, train_y, scoring='f1_macro', cv=10)

In [17]:
scores

array([0.68535555, 0.67808959, 0.68395892, 0.6814135 , 0.68327091,
       0.68599579, 0.68932571, 0.6993718 , 0.68589725, 0.68248117])

In [18]:
print("Accuracy: %0.4f (+/- %0.3f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.6855 (+/- 0.011)


In [19]:
rand_fr_1.fit(train_X,train_y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [20]:
rand_fr_1.score(test_X,test_y)

0.6905333333333333

In [21]:
from sklearn.metrics import classification_report,confusion_matrix
 
predictions = rand_fr_1.predict(test_X)
 
print(confusion_matrix(test_y,predictions))
print(classification_report(test_y,predictions))

[[4323 1819 1096  262]
 [2092 4187  625  596]
 [ 903  488 5869  240]
 [ 169  599  395 6337]]
             precision    recall  f1-score   support

     2month       0.58      0.58      0.58      7500
      month       0.59      0.56      0.57      7500
   retained       0.74      0.78      0.76      7500
       week       0.85      0.84      0.85      7500

avg / total       0.69      0.69      0.69     30000



In [22]:
np.size(predictions)

30000

## After Checking validation set

### Devide month&2month label for train_set

In [23]:
rand_fr_1.predict(train_X)

array(['month', 'month', 'week', ..., 'month', '2month', '2month'],
      dtype=object)

In [24]:
train_X_s = rand_fr_1.predict(train_X)

In [25]:
train_X_1 = pd.DataFrame({'acc_id': train_X_id, 'pr_label': train_X_s})

In [26]:
train_X_1['pr_label'].value_counts()

2month      17658
month       17579
week        17419
retained    17344
Name: pr_label, dtype: int64

In [27]:
train_X_1_wr = train_X_1[(train_X_1['pr_label'] == 'week') | (train_X_1['pr_label'] == 'retained')]
train_X_1_mm = train_X_1[(train_X_1['pr_label'] == 'month') | (train_X_1['pr_label'] == '2month')]

In [28]:
train_X_1_mm.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 35237 entries, 9787 to 77718
Data columns (total 2 columns):
acc_id      35237 non-null object
pr_label    35237 non-null object
dtypes: object(2)
memory usage: 825.9+ KB


In [29]:
sec_train_set = pd.merge(train_X_1_mm, train_activity_label, on='acc_id')

In [30]:
sec_train_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 35237 entries, 0 to 35236
Data columns (total 40 columns):
acc_id                      35237 non-null object
pr_label                    35237 non-null object
wk                          35237 non-null float64
cnt_dt                      35237 non-null float64
play_time                   35237 non-null float64
npc_exp                     35237 non-null float64
npc_hongmun                 35237 non-null float64
quest_exp                   35237 non-null float64
quest_hongmun               35237 non-null float64
item_hongmun                35237 non-null float64
game_combat_time            35237 non-null float64
get_money                   35237 non-null float64
duel_cnt                    35237 non-null float64
duel_win                    35237 non-null float64
partybattle_cnt             35237 non-null float64
partybattle_win             35237 non-null float64
cnt_enter_inzone_solo       35237 non-null float64
cnt_enter_inzone_light    

In [31]:
sec_train_set['label'].value_counts()

month       17268
2month      17267
retained      493
week          209
Name: label, dtype: int64

In [32]:
sec_train_set.head(15)

acc_id pr_label        wk  \
0   18af352a486615c71e794eabd7de7dcbcfaaa8025d8c72...    month  5.000000   
1   89f84ffac2303e3ce14df60c77c834d04de191ab467738...    month  8.000000   
2   98cf8ba124fd558aa93872b166090d85d6546425985ea8...    month  4.500000   
3   58ebaa770abbf2efdad1f75d1afe5d6ebcd088358883c5...    month  8.000000   
4   b67369a328dc712bb389aff71ab3ed07d8b085c8255c47...    month  8.000000   
5   15b34c0416fbbbb2f29d4ecbbd14574b119630d668cb3f...   2month  7.000000   
6   6c0671055db704e668961b095fff4648e8fb9f240df755...    month  8.000000   
7   7e5b8124af03d74fe89e1bcf8d820b6f703cee8d8221d0...    month  4.142857   
8   40e0dc39cd30cbdec6c7cd7e1cf892470350c633e55d98...   2month  7.500000   
9   0b3c46f8c93b501db17cd80758b2bb7579ae45f7e942a5...    month  7.000000   
10  5b5f1021954b7b92994e887ef1aef547ddb447a7be9658...    month  4.500000   
11  60d0202368141926f7e348aceb0f2449149cbae9ef52ff...    month  6.000000   
12  e10bf354eefe5aae8eb97933a355f76637234ef470c67e...   2month  5.400000   
13  954f5bd82dfe2e238b492df46e050607fcb99d717b7393...    month  7.000000   
14  7effcdcfbbf30f3063bca0673d3c3b0fcbb5a1d93dc407...    month  8.000000   

      cnt_dt  play_time   npc_exp  npc_hongmun  quest_exp  quest_hongmun  \
0   4.833333  -0.528608 -0.157050    -0.286200  -0.027648      -0.153857   
1   3.000000  -0.659798 -0.231874    -0.290803  -0.250423      -0.487666   
2   6.750000  -0.264199 -0.231874    -0.157795  -0.250423      -0.418289   
3   4.000000  -0.659660 -0.231874    -0.290803  -0.250423      -0.487666   
4   4.000000  -0.648216 -0.231021    -0.290803  -0.245978      -0.487666   
5   3.666667  -0.654104 -0.231590    -0.290803  -0.248942      -0.487666   
6   2.000000  -0.661381 -0.231874    -0.290803  -0.250423      -0.487666   
7   5.285714  -0.424249 -0.231874    -0.230185  -0.250423      -0.463104   
8   4.000000   2.013967  5.670308    -0.194671   5.276536       3.816281   
9   1.000000  -0.574565 -0.231874    -0.263985  -0.250423      -0.468324   
10  6.375000  -0.359622 -0.231874    -0.133133  -0.250423      -0.435403   
11  5.200000  -0.655684 -0.231874    -0.290803  -0.250423      -0.487666   
12  2.600000  -0.658231 -0.231874    -0.290803  -0.250423      -0.487666   
13  3.000000  -0.654289 -0.231590    -0.290803  -0.248942      -0.487666   
14  5.000000  -0.658839 -0.231874    -0.290803  -0.250423      -0.487666   

    item_hongmun   ...    normal_chat  whisper_chat  district_chat  \
0      -0.302199   ...      -0.032859     -0.161998      -0.016574   
1      -0.306354   ...      -0.034038     -0.231827      -0.016574   
2      -0.256754   ...      -0.034038     -0.150189      -0.016574   
3      -0.306354   ...      -0.034038     -0.231827      -0.016574   
4      -0.306354   ...      -0.034038     -0.231827      -0.016574   
5      -0.306354   ...      -0.034038     -0.231827      -0.016574   
6      -0.306354   ...      -0.034038     -0.231827      -0.016574   
7      -0.276675   ...      -0.034038     -0.163172      -0.016574   
8      -0.306354   ...       0.167551     -0.231827      -0.016574   
9      -0.281424   ...      -0.034038     -0.207181      -0.016574   
10     -0.249223   ...      -0.034038     -0.153270      -0.016574   
11     -0.306354   ...      -0.034038     -0.231827      -0.016574   
12     -0.306354   ...      -0.034038     -0.231827      -0.016574   
13     -0.306354   ...      -0.034038     -0.231827      -0.016574   
14     -0.306354   ...      -0.034038     -0.231827      -0.016574   

    party_chat  guild_chat  faction_chat  cnt_use_buffitem  gathering_cnt  \
0    -0.268693   -0.343293     -0.024028         -0.389936      -0.027758   
1    -0.275174   -0.343293     -0.024028         -0.503692      -0.027758   
2    -0.275174   -0.343293     -0.024028         -0.029708      -0.027758   
3    -0.275174   -0.343293     -0.024028         -0.503692      -0.027758   
4    -0.275174   -0.343293     -0.024028         -0.498275      -0.027758   
5    -0.275174   -0.343293    

### Devide month&2month label for test_set (validation)

In [33]:
test_X_s = predictions

In [34]:
test_X_1 = pd.DataFrame({'acc_id': test_X_id, 'pr_label': test_X_s})

In [35]:
test_X_1['pr_label'].value_counts()

retained    7985
2month      7487
week        7435
month       7093
Name: pr_label, dtype: int64

In [36]:
test_X_1_wr = test_X_1[(test_X_1['pr_label'] == 'week') | (test_X_1['pr_label'] == 'retained')]
test_X_1_mm = test_X_1[(test_X_1['pr_label'] == 'month') | (test_X_1['pr_label'] == '2month')]

In [37]:
test_X_1_mm.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14580 entries, 7600 to 13096
Data columns (total 2 columns):
acc_id      14580 non-null object
pr_label    14580 non-null object
dtypes: object(2)
memory usage: 341.7+ KB


In [38]:
sec_test_set = pd.merge(test_X_1_mm, train_activity_label, on='acc_id')

In [39]:
sec_test_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14580 entries, 0 to 14579
Data columns (total 40 columns):
acc_id                      14580 non-null object
pr_label                    14580 non-null object
wk                          14580 non-null float64
cnt_dt                      14580 non-null float64
play_time                   14580 non-null float64
npc_exp                     14580 non-null float64
npc_hongmun                 14580 non-null float64
quest_exp                   14580 non-null float64
quest_hongmun               14580 non-null float64
item_hongmun                14580 non-null float64
game_combat_time            14580 non-null float64
get_money                   14580 non-null float64
duel_cnt                    14580 non-null float64
duel_win                    14580 non-null float64
partybattle_cnt             14580 non-null float64
partybattle_win             14580 non-null float64
cnt_enter_inzone_solo       14580 non-null float64
cnt_enter_inzone_light    

# Second Model

In [40]:
train_X_2 = sec_train_set.drop(['acc_id','label','pr_label'],axis=1)
train_y_2 = sec_train_set['label']
test_X_2 = sec_test_set.drop(['acc_id','label','pr_label'],axis=1)
test_y_2 = sec_test_set['label']

In [41]:
rand_fr_2 = RandomForestClassifier(random_state=42)

In [42]:
scores = cross_val_score(rand_fr_2, train_X_2, train_y_2, scoring='f1_macro', cv=10)

C:\Anaconda_\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Anaconda_\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [43]:
scores

array([0.33007666, 0.33749153, 0.33294596, 0.33421504, 0.33495974,
       0.3345535 , 0.32825112, 0.343438  , 0.33512067, 0.32970816])

In [44]:
print("Accuracy: %0.4f (+/- %0.3f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.3341 (+/- 0.008)


In [45]:
rand_fr_2.fit(train_X_2,train_y_2)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [46]:
rand_fr_2.score(test_X_2,test_y_2)

0.5779149519890261

In [47]:
predictions = rand_fr_2.predict(test_X_2)
 
print(confusion_matrix(test_y_2,predictions))
print(classification_report(test_y_2,predictions))

[[4428 1679   29    6]
 [2265 3988   21    5]
 [ 982  400    9    0]
 [ 203  564    0    1]]
             precision    recall  f1-score   support

     2month       0.56      0.72      0.63      6142
      month       0.60      0.64      0.62      6279
   retained       0.15      0.01      0.01      1391
       week       0.08      0.00      0.00       768

avg / total       0.51      0.58      0.53     14580



### Scaling for SVC

In [52]:
from sklearn import preprocessing

scaler = preprocessing.MinMaxScaler()

train_X_2_scaled = scaler.fit_transform(train_X_2)

train_X_2_scaled

array([[3.33333333e-01, 6.38888889e-01, 2.50600019e-02, ...,
        1.57185629e-02, 5.42101086e-20, 0.00000000e+00],
       [1.00000000e+00, 3.33333333e-01, 3.24485811e-04, ...,
        0.00000000e+00, 5.42101086e-20, 3.46944695e-18],
       [2.22222222e-01, 9.58333333e-01, 7.49137968e-02, ...,
        6.54940120e-02, 5.42101086e-20, 0.00000000e+00],
       ...,
       [1.00000000e+00, 3.33333333e-01, 2.36650859e-03, ...,
        7.48502994e-04, 5.42101086e-20, 3.46944695e-18],
       [2.22222222e-01, 7.08333333e-01, 1.17392999e-03, ...,
        0.00000000e+00, 5.42101086e-20, 0.00000000e+00],
       [1.00000000e+00, 1.66666667e-01, 1.84061779e-03, ...,
        0.00000000e+00, 5.42101086e-20, 3.46944695e-18]])

### Grid Search for SVC

In [60]:

from sklearn import svm
from sklearn. model_selection import GridSearchCV

def svc_param_selection(X, y, nfolds):
    Cs = [0.1, 1, 10, 100]
    gammas = [0.1, 1, 5, 100]
    param_grid = {'C': Cs, 'gamma' : gammas}
    grid_search = GridSearchCV(svm.SVC(kernel='rbf'), param_grid, cv=nfolds)
    grid_search.fit(X, y)
    grid_search.best_params_
    return grid_search.best_params_
    

In [ ]:
svc_param_selection(train_X_2_scaled, train_y_2, 5)

In [ ]:
scaler = preprocessing.MinMaxScaler()

test_X_2_scaled = scaler.fit_transform(test_X_2)

test_X_2_scaled

In [62]:
grid.search.predict()

array([[5.55555556e-01, 9.33333333e-01, 2.62704922e-01, ...,
        7.43392070e-02, 0.00000000e+00, 1.22727273e-01],
       [4.22222222e-01, 2.66666667e-01, 8.97806769e-04, ...,
        1.65198238e-04, 0.00000000e+00, 0.00000000e+00],
       [4.22222222e-01, 3.00000000e-01, 9.60027377e-04, ...,
        1.65198238e-04, 0.00000000e+00, 0.00000000e+00],
       ...,
       [2.96296296e-01, 2.22222222e-01, 5.50225374e-04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 3.33333333e-01, 3.78813700e-04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.33333333e-01, 5.00000000e-01, 8.98538776e-04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [ ]:
grid.search.predict(test_X_2)

# Test set

In [ ]:
rand_fr_2 = RandomForestClassifier()

In [ ]:
scores = cross_val_score(rand_fr, train_X, train_y, scoring='f1_macro', cv=10)

In [ ]:
s = rand_fr.predict(real_test)

In [ ]:
s

In [ ]:
real_test_1 = pd.DataFrame({'acc_id': real_test_id, 'label': s})

In [ ]:
real_test_1.info()

In [ ]:
real_test_1['label'].value_counts()

In [ ]:
real_test_1_wr = real_test_1[(real_test_1['label'] == 'week') | (real_test_1['label'] == 'retained')]

In [ ]:
real_test_1_mm = real_test_1[(real_test_1['label'] == 'month') | (real_test_1['label'] == '2month')]

In [ ]:
real_test_1_wr['label'].value_counts()

In [ ]:
real_test_1_mm['label'].value_counts()

In [ ]:
real_test_1_mm.info()